                                                        Logistics Regression using SocialNetwork.csv                                                            

In [1]:
import numpy as numpy
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset=pd.read_csv(r"C:\Users\Asus\Ethans\ml\logisticregression\Copy of Social_Network_Ads.csv")
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [5]:
#Selecting independebt (X) and dependent (y) variables
# X= features(input data)
# iloc[:,[2,3]] means:
# ":" all rows
# "[2,3]" take 2 column and 3 column only
# These are the two inputs features we will use for prediction
X=dataset.iloc[:,[2,3]].values
y=dataset.iloc[:,4].values


In [6]:
# Splitting the dataset into the training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test=train_test_split(X,y, test_size=0.25, random_state=42)

In [7]:
"""
Quick rule for balance in classification
A dataset is considered balanced if no class is extremely larger than the other. Normally, if one classs is more than 60%-70% of the data, the dataset becomes 
imbalanced
"""

'\nQuick rule for balance in classification\nA dataset is considered balanced if no class is extremely larger than the other. Normally, if one classs is more than 60%-70% of the data, the dataset becomes \nimbalanced\n'

In [8]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [9]:
# Feature scaling:
# We scale features so that all values have a similar range
# StandardScaler converts the data into a standard form:
# mean= 0 and sd = 1
# This helps the model learn better and faster

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

# Training data to fit + transform
# sc.fit_transform() -->> scaler ko training data ke hisaab se sikhaata hai
# aur fir data ko scale karta hai
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)  #scale test data using same rules
X_train

array([[ 1.8925893 ,  1.52189404],
       [ 0.1250379 ,  0.03213212],
       [ 0.9106163 , -1.31157471],
       [-1.34792161, -1.48684082],
       [-0.169554  , -0.58129926],
       [-0.56234321,  2.33980255],
       [ 1.0088136 , -1.19473064],
       [-0.75873781,  1.08372877],
       [ 2.1871812 , -1.04867555],
       [ 0.0268406 , -0.25997806],
       [-0.46414591, -1.1363086 ],
       [ 0.1250379 ,  0.03213212],
       [ 1.6961947 , -0.90262046],
       [ 1.1070109 , -0.90262046],
       [ 0.5178271 ,  1.22978386],
       [-1.05332971, -1.4576298 ],
       [-1.15152701, -1.54526286],
       [-0.0713567 ,  0.67477452],
       [ 0.4196298 , -0.46445519],
       [-0.2677513 , -0.25997806],
       [-0.85693511,  0.14897619],
       [ 0.0268406 ,  0.29503128],
       [ 0.7142217 , -1.28236369],
       [ 1.5979974 ,  1.11293979],
       [ 0.812419  , -1.36999675],
       [-1.44611891, -1.22394166],
       [-0.0713567 ,  0.14897619],
       [ 0.4196298 , -0.14313399],
       [-0.2677513 ,

In [10]:
# Fitting Logistic Regression to Training set
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [11]:
# Prediting the Test set results
y_pred=classifier.predict(X_test)
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0], dtype=int64)

In [13]:
# Making thr Confusion Matrix (correct and incorrect matrix)
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score,recall_score
cm = confusion_matrix(y_test,y_pred)
accuracy_score=accuracy_score(y_test,y_pred)

print(accuracy_score)
print(cm)
print("\n Precision")
print(precision_score(y_test,y_pred))

print("\n recall:")
print(recall_score(y_test,y_pred))

print("\n f1 score")
print(f1_score(y_test,y_pred))

0.86
[[61  2]
 [12 25]]

 Precision
0.9259259259259259

 recall:
0.6756756756756757

 f1 score
0.7812500000000001
